######################################################################
# Automatically generated by qmake (3.0) Thu Nov 10 09:28:06 2016
######################################################################

QT += testlib
TEMPLATE = app
TARGET = UnitTests
INCLUDEPATH += .

# Input
HEADERS += setpassworddialogtest.h
SOURCES += setpassworddialogtest.cpp
